<script src="./index.js"></script>
<template lang="pug">
  transition-group(
    appear
    tag="div"
    :class="$style.wrapper"
  )
    div(
      v-text="theName"
      key="name"
      :class="$style.theName"
    )
    section(
      :class="$style.section"
      key="list"
    )
      BaseTypography(
        :level="3"
        text="人名漢字を探す（外部リンク）"
        :class="$style.sectionTitle"
      )
      ul(:class="$style.linkList")
        li(
          :class="$style.li"
          v-for="(val, index) in nameList"
          :key="index"
        )
          LinkButtonWithIcon(
            iconName="ExternalLinkIcon"
            :text="val"
            :url="`${kanjiLink}${val}`"
            :class="$style.button"
          )
    section(
      :class="$style.section"
      key="share"
    )
      BaseTypography(
        :level="3"
        :text="`\"${theName}\"を共有する`"
        :class="$style.sectionTitle"
      )
      div(:class="$style.shareUrl")
        div(
          :class="$style.urlBox"
          v-text="theUrl"
        )
        transition-group(tag="div")
          p(
            key="success"
            v-if="isVisibleSuccess"
            v-text="'👍👍コピーできました👍👍'"
            :class="$style.success"
          )
          p(
            key="fail"
            v-if="isVisibleFailure"
            v-text="'😥失敗です😥'"
            :class="$style.fail"
          )
        ButtonWithIcon(
          iconName="LinkIcon"
          iconPosition="left"
          text="URLをコピー"
          :class="$style.button"
          @click.native.prevent="copyToClipboard()"
        )
</template>
<style lang="scss" module src="./index.scss"></style>
